#!/usr/bin/env ansible-playbook --ask-become-pass
- hosts: localhost
  connection: local
  tasks:
  - debug:
      msg: Check we are running in the directory of the script
    failed_when: not ansible_env.PWD.endswith('/mac-ansible')

  - name: Check we are on a supported version of macOS (High Sierra or later)
    shell: sw_vers -productVersion
    register: macosversion
    failed_when: macosversion.stdout is version('10.13', '<')
    changed_when: false

  - name: Check Xcode is installed
    shell: xcode-select -p
    register: xcodeselectpath
    failed_when: xcodeselectpath.rc != 0
    changed_when: false

- hosts: localhost
  connection: local
  roles:
  - bruno_mac
