- name: Update homebrew
  homebrew:
    name: git
    state: latest
    update_homebrew: true
  tags:
  - brew

- name: Install homebrew packages
  homebrew:
    name: '{{ homebrew_packages }}'
    state: latest
  tags:
  - brew

- name: Install homebrew cask packages
  command: brew install {{ homebrew_cask_packages|join(" ") }}
  tags:
  - brew

- name: homebrew cleanup
  command: brew cleanup

- name: uv install latest Pythons
  command: uv python install --reinstall {{ item }}
  loop: '{{ uv_python_versions }}'
  register: uv_python_install
  changed_when: "'All requested versions already installed' not in uv_python_install.stderr"
  tags:
  - uv

- name: uv install tools
  command: >
    uv tool install
    --python 3.12
    {{ item.name }}
    {% if item.with is defined %}
    {% for w in item.with %}--with {{ w }}{% endfor %}
    {% endif %}
  loop: '{{ uv_tools }}'
  register: uv_tool_install
  changed_when: "'already installed' not in uv_tool_install.stderr"
  tags:
  - uv

- name: uv upgrade tools
  command: >
    uv tool upgrade
    {{ item.name }}
    {% if item.with is defined %}
    {% for w in item.with %}--upgrade-package {{ w }}{% endfor %}
    {% endif %}
  loop: '{{ uv_tools }}'
  register: uv_upgrade
  changed_when: "'Nothing to upgrade' not in uv_upgrade.stderr"
  tags:
  - uv