# Do sudo using Touch ID
- name: Set sudo via Touch ID if not setup
  lineinfile:
    path: /etc/pam.d/sudo
    regexp: '^auth.*sufficient.*pam_tid.so$'
    insertafter: '^#'
    firstmatch: yes
    line: 'auth       sufficient     pam_tid.so'
  become: yes      
  tags:
    - touchid
