homebrew_packages:
- autojump
- awscli
- browniebroke/tap/stsmfa-cli
- cmatrix
- coreutils
- doctl
- duf
- ffmpeg
- flyctl
- gdal
- git
- gh
- gnu-sed
- gpg
- heroku/brew/heroku
- htop
- ipython
- jq
- jupyterlab
- mackup
- nvm
- openssl
- pandoc
- pkg-config
- pwgen
- rclone
- rich-cli
- ripgrep
- rsync
- rtmpdump
- sd
- shellcheck
- sqlite
- terraform
- tree
- uv
- dive
- watch
- wget
- yt-dlp
- zlib
- zsh-completions

homebrew_cask_packages:
- 1password
- 1password-cli
- backblaze
- backblaze-downloader
- cryptomator
- cursor
- daisydisk
- discord
- dropbox
- expressvpn
- figma
- firefox
- ghostty
- google-chrome
- homebrew/cask/docker
- insomnia
- jetbrains-toolbox
- krita
- notion
- raspberry-pi-imager
- raycast
- rectangle
- slack
- spotify
- stats
- the-unarchiver
- visual-studio-code
- vlc
- whatsapp
- zoom

uv_python_versions:
- "3.14"
- "3.14t"
- "3.13"
- "3.13t"
- "3.12"
- "3.11"
- "3.10"
- "3.9"

uv_tools:
- name: black
- name: browniebroke-utils
- name: cookiecutter
- name: copier
- name: django-upgrade
- name: flake8
- name: isort
- name: mypy
- name: pre-commit
  with:
  - pre-commit-uv
- name: poetry
- name: pyupgrade
- name: ruff
- name: tox
  with:
  - tox-uv
- name: twine
- name: yt-dlp
